PenDesign.WebUI/Areas/Admin/Controllers/ProjectController.cs
using PenDesign.Core.Interface.Service.BasicServiceInterface;
using PenDesign.Core.Model;
using PenDesign.Data;
using PenDesign.WebUI.Authencation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using PenDesign.WebUI.Areas.Admin.Models;

namespace PenDesign.WebUI.Areas.Admin.Controllers
{
    [CustomAuthorize(Roles = "Admin, Users")]
    public class ProjectController : ApiController
    {

        private UserFactory _userFactory;
        private string _userId;
        private IProjectService _projectService;
        private IProjectMappingService _projectMappingService;
        private IProjectImageService _projectImageService;
        private INewsService _newsService;
        private INewsMappingService _newsMappingService;
        private IProjectImageMappingService _projectImageMappingService;



        public ProjectController(IProjectService projectService, IProjectMappingService projectMappingService,
                                    IProjectImageService projectImageService, IProjectImageMappingService projectImageMappingService,
                                        INewsService newsService, INewsMappingService newsMappingService, UserFactory userFactory)
        {
            this._projectService = projectService;
            this._projectMappingService = projectMappingService;

            this._projectImageService = projectImageService;
            this._projectImageMappingService = projectImageMappingService;

            this._newsService = newsService;
            this._newsMappingService = newsMappingService;

            this._userFactory = userFactory;
            this._userId = _userFactory.GetUserId(User.Identity.Name);
        }

        // GET: api/Banner
        public IQueryable<AdminProjectVM> Get()
        {
            try
            {
                var adminProjectVM = new List<AdminProjectVM>();

                var projectModel = _projectService.GetMany(n => n.Type == 1 && n.Deleted == false).AsQueryable();

                foreach (var bm in projectModel)
                {
                    foreach (var pi in bm.ProjectImages.ToList())
                    {
                        if (pi.Deleted)
                            bm.ProjectImages.Remove(pi);
                    }
                    var model = new AdminProjectVM()
                    {
                        Projects = bm,
                        EditedUser = _userFactory.GetUserNameById(bm.ModifiedById)
                    };
                    adminProjectVM.Add(model);
                }
                return adminProjectVM.AsQueryable();
            }
            catch (Exception)
            {
                throw new Exception("Lỗi! Không thể tải dữ liệu!");
            }
        }


        // POST: api/Banner
        public HttpResponseMessage Post([FromBody] AdminProjectVMInput AdminProjectVMInput)
        {
            try
            {
                if (AdminProjectVMInput.ResourceUrl.ToString() != "")
                {
                    if (AdminProjectVMInput.ResourceUrl.ToString().Contains("/Content"))
                    {
                        AdminProjectVMInput.ResourceUrl = AdminProjectVMInput.ResourceUrl;
                        AdminProjectVMInput.Thumbnail = AdminProjectVMInput.Thumbnail;
                    }
                    else
                    {
                        AdminProjectVMInput.Thumbnail = "/Content/UploadFiles/images/images/thumb_" + AdminProjectVMInput.ResourceUrl;
                        AdminProjectVMInput.ResourceUrl = "/Content/UploadFiles/images/images/" + AdminProjectVMInput.ResourceUrl;
                    }
                }
                else
                {
                    AdminProjectVMInput.ResourceUrl = "/Content/images/No_image_available.png";
                    AdminProjectVMInput.Thumbnail = "/Content/images/No_image_available.png";
                }

                var name = AdminProjectVMInput.Name;
                var intro = AdminProjectVMInput.Intro;
                var keyword = AdminProjectVMInput.Keyword;
                var description = AdminProjectVMInput.Description;
                var detail = AdminProjectVMInput.Detail;
                var metaData = AdminProjectVMInput.MetaData;
                var thumbnail = AdminProjectVMInput.Thumbnail;
                var resourceUrl = AdminProjectVMInput.ResourceUrl;

                var maxOrder = _projectService.Entities.Where(p => p.Type == 1 && p.Deleted == false).Max(p => p.ZOrder);

                var projectModel = new Project()
                {
                    Name = name, Type = 1, ZOrder = maxOrder + 1, Status = true, Deleted = false,
                    CreatedById = _userId, ModifiedById = _userId
                };
                _projectService.Add(projectModel);

                var justAddedProjectId = _projectService.Entities.Max(b => b.Id);

                /*
                 add project image
                 */

                var projectImage = new ProjectImage()
                {
                    ProjectId = justAddedProjectId, Thumbnail = thumbnail, ResourceUrl = resourceUrl,
                    Type = 1, ZOrder = 1, Status = true, Deleted = false,
                    CreatedById = _userId, ModifiedById = _userId
                };
                _projectImageService.Add(projectImage);

                var justAddedProjectImageId = _projectImageService.Entities.Max(b => b.Id);
                var projectImageMappingList = new List<ProjectImageMapping>()
                {
                    new ProjectImageMapping()
                    {
                        ProjectImageId = justAddedProjectImageId, LanguageId = 129, Deleted = false, Status = true,
                        Name = name, Description = "",
                        CreatedById = _userId, ModifiedById = _userId
                    },
                    new ProjectImageMapping()
                    {
                        ProjectImageId = justAddedProjectImageId, LanguageId = 29, Deleted = false, Status = true,
                        Name = name + " - EN", Description = "",
                        CreatedById = _userId, ModifiedById = _userId
                    }
                };
                foreach (var pim in projectImageMappingList)
                {
                    _projectImageMappingService.Add(pim);
                }



                /*
                 Add News
                 */

                var news = new News();
                news.ProjectId = justAddedProjectId;
                news.Name = AdminProjectVMInput.Name;
                news.CreatedById = _userId;
                news.ModifiedById = _userId;
                news.Deleted = false;
                news.Status = true;
                news.ZOrder = 1;
                _newsService.Add(news);

                var justAddedNewsId = _newsService.Entities.Max(b => b.Id);
                var newsMappingsModels = new List<NewsMapping>()
                {
                    new NewsMapping()
                    {
                        NewsId = justAddedNewsId, LanguageId = 129, Status = true, Deleted = false,
                        Title = news.Name, Intro = intro, Keyword = keyword, Description = description, MetaData = metaData, Detail = detail, 
                        CreatedById = _userId, ModifiedById = _userId,
                    },
                    new NewsMapping()
                    {
                        NewsId = justAddedNewsId, LanguageId = 29, Status = true,
                        Title = "", Intro = "", Keyword = "", Description = "", Deleted = false, Detail = "", MetaData = "",
                        CreatedById = _userId, ModifiedById = _userId
                    }
                };
                foreach (var nm in newsMappingsModels)
                {
                    _newsMappingService.Add(nm);
                }

                var responseMessage = new { message = "Thêm thành công!" };
                return Request.CreateResponse(HttpStatusCode.OK, responseMessage);
            }
            catch (Exception)
            {
                var responseMessage = new { message = "Lỗi! Vui lòng thử lại sau!" };
                return Request.CreateResponse(HttpStatusCode.InternalServerError, responseMessage);
                throw;
            }
        }

        // PUT: api/Banner/5
        public HttpResponseMessage Put([FromBody] Project project)
        {
            try
            {
                project.ModifiedById = _userId;
                project.ModifiedDateTime = DateTime.Now;

                if (project.ProjectImages.Count() > 0)
                {
                    foreach (var projectImageModel in project.ProjectImages)
                    {
                        projectImageModel.ModifiedById = _userId;
                        projectImageModel.ModifiedDateTime = DateTime.Now;
                        _projectImageService.Update(projectImageModel);
                    }
                }

                if (project.News.Count() > 0)
                {
                    foreach (var projectNew in project.News)
                    {
                        projectNew.ModifiedById = _userId;
                        projectNew.ModifiedDateTime = DateTime.Now;
                        _newsService.Update(projectNew);

                        foreach (var projectNewsMapping in projectNew.NewsMappings)
                        {
                            projectNewsMapping.ModifiedById = _userId;
                            projectNewsMapping.ModifiedDateTime = DateTime.Now;

PenDesign.WebUI/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PenDesign.Core.Interface.Service.BasicServiceInterface;
using PenDesign.WebUI.Models;
using PenDesign.Common.Utils;
using PenDesign.WebUI.Infrastructure;

namespace PenDesign.WebUI.Controllers
{
    public class NewsController : Controller
    {
        private INewsCategoryService _newsCategoryService;
        private INewsService _newsService;
        private int ItemPerPage;
        private int LanguageId;

        public NewsController(INewsCategoryService newsCategoryService, INewsService newsService
            )
        {
            this._newsCategoryService = newsCategoryService;
            this._newsService = newsService;

            this.LanguageId = int.Parse(Cookies.ReadCookie("PenDesign:Language", "129"));

            ItemPerPage = AppSettings.ItemsPerPage;
        }

        // GET: News
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListByTrends(int? newsCategoryId, int page = 1)
        {
            if (newsCategoryId == null)
                return View();

            var newsCategoryModel = _newsCategoryService.Get(n => n.Id == newsCategoryId)
                                                        .NewsCategoryMappings
                                                        .SingleOrDefault(n => n.LanguageId == LanguageId);
            ViewBag.newsCategoryName = newsCategoryModel.Title;
            ViewBag.Keyword = newsCategoryModel.Keyword;
            ViewBag.Description = newsCategoryModel.Description;
            ViewBag.MetaData = newsCategoryModel.MetaData;

            var NewsVM = new NewsVM();
            NewsVM.PagingItems = _newsService.Page(n => n.NewsCategoryId == newsCategoryId && n.Status == true && n.Deleted == false, n => n.ZOrder, page, ItemPerPage, true);
            NewsVM.News = NewsVM.PagingItems.Entities;
            return View(NewsVM);
        }

        public ActionResult ListByCustomers(int? newsCategoryId, int page = 1)
        {
            if (newsCategoryId == null)
                return View();

            var newsCategoryModel = _newsCategoryService.Get(n => n.Id == newsCategoryId)
                                                        .NewsCategoryMappings
                                                        .SingleOrDefault(n => n.LanguageId == LanguageId);
            ViewBag.newsCategoryName = newsCategoryModel.Title;
            ViewBag.Keyword = newsCategoryModel.Keyword;
            ViewBag.Description = newsCategoryModel.Description;
            ViewBag.MetaData = newsCategoryModel.MetaData;

            var NewsVM = new NewsVM();
            NewsVM.PagingItems = _newsService.Page(n => n.NewsCategoryId == newsCategoryId && n.Status == true && n.Deleted == false, n => n.ZOrder, page, ItemPerPage, true);
            NewsVM.News = NewsVM.PagingItems.Entities;
            return View(NewsVM);
        }

        public ActionResult Detail(int id)
        {
            var newsCategoryModel = _newsService.Get(n => n.Id == id)
                                                .NewsCategory
                                                .NewsCategoryMappings
                                                .Where(nc => nc.LanguageId == LanguageId)
                                                .SingleOrDefault();

            if (newsCategoryModel == null) return View();

            ViewBag.newsCategoryName = newsCategoryModel.Title.Trim();

            var newsModel = _newsService.Get(n => n.Id == id && n.Status == true && n.Deleted == false)
                                        .NewsMappings
                                        .SingleOrDefault(nm => nm.LanguageId == LanguageId && nm.Status == true && nm.Deleted == false);

            return View(newsModel);
        }

        [ChildActionOnly]
        public PartialViewResult _SidebarNews(int newsCategoryId)
        {
            var newsCategoryModel = _newsCategoryService.Get(n => n.Id == newsCategoryId && n.Status == true && n.Deleted == false);
            if (newsCategoryModel == null) return PartialView();

            ViewBag.newsCategoryName = newsCategoryModel.NewsCategoryMappings.SingleOrDefault(nm => nm.LanguageId == LanguageId && nm.Status == true && nm.Deleted == false)
                                                                              .Title;
            ViewBag.newsCategoryId = newsCategoryModel.Id;

            var newsCategory = _newsService.GetMany(n => n.NewsCategoryId == newsCategoryId && n.Status == true && n.Deleted == false)
                                            .OrderBy(n => n.ZOrder)
                                            .Take(6);

            return PartialView("_SidebarNews", newsCategory);
        }
    }
}

PenDesign.WebUI/Views/Project/Detail.cshtml
@using PenDesign.Common.HelperMethod
@model PenDesign.Core.Model.NewsMapping

@{
    ViewBag.Title = Model.Title + " | Dự án";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

@section SEO{
    <meta name="keywords" content="@Model.Keyword">
    <meta name="description" content="@Model.Description">
    @Html.Raw(Model.MetaData)
}

<div class="content">
    <div class="container_12">
        <div class="breadcrumb">
            <a href="/" title="Trang chủ">Trang chủ</a> / <a href="/du-an" title="Dự án">Dự án</a> / @Model.Title
        </div>
        <div class="grid_9">
            @if (Model != null)
            {
                <h1 class="news-title">@Model.Title</h1>
                @Html.Raw(Model.Detail)
            }
            else
            {
                <p>Bài viết không tồn tại hoặc đã bị xóa!</p>
            }
        </div>

        <div class="grid_3">
            @{Html.RenderAction("_SidebarNews", "News", new { newsCategoryId = 1 });}
            @{Html.RenderAction("_SidebarNews", "News", new { newsCategoryId = 2 });}
        </div>
    </div>
</div>



PenDesign.WebUI/Views/Project/Index.cshtml
@*@using PenDesign.Common.HelperMethod
@model IEnumerable<PenDesign.Core.Model.Project>

@{
    ViewBag.Title = "Dự án";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

@section ScriptsHeader{

    <link href="~/Content/colorbox/colorbox.css" rel="stylesheet" />
    <script src="~/Content/colorbox/jquery.colorbox-min.js"></script>
}

<div class="content">
    <div class="container_12">
        <div class="breadcrumb">
            <a href="/" title="Trang chủ">Trang chủ</a> / Dự án
        </div>
        <div class="grid_12">
            <h2>Dự án</h2>
        </div>
        <div class="clear cl1"></div>
        <div class="serv">
            @if (Model != null)
            {
                var i = 1;
                foreach (var item in Model)
                {
                    <div class="grid_4">
                        @{
                            var firstImage = item.ProjectImages.First();
                            foreach (var image in item.ProjectImages)
                            {
                                var imageName = image.ProjectImageMappings.Where(m => m.LanguageId == 129).SingleOrDefault().Name;
                                if (image.Equals(firstImage))
                                {
                                    <a class="gal group-@i" href="@image.ResourceUrl" title="@imageName">
                                        <img src="@image.Thumbnail" class="img-responsive" alt="@imageName"/>
                                    </a>
                                }
                                else
                                {
                                    <a class="group-@i hidden" href="@image.ResourceUrl" title="@imageName"></a>
                                }
                            }
                        }
                        <div class="text1">
                            <a href="#">@item.ProjectMappings.Where(m => m.LanguageId == 129).SingleOrDefault().Title</a>
                        </div>
                        @Html.Raw(item.ProjectMappings.Where(m => m.LanguageId == 129).SingleOrDefault().Intro)
                        <div class="alright">
                            <a href="#" class="btn">Xem thêm</a>
                        </div>
                    </div>
                    if (i > 1 && i%3 == 0)
                    {
                        <div class="clear cl1"></div>
                    }
                    var content = "$('.group-" + i + "' ).colorbox({rel: 'group-" + i + "'});";
                    <script>
                        @Html.Raw(content)
                    </script>
                    i++;
                }
            }

        </div>
    </div>
    @Html.Paging(new PagingOptions(ViewBag.pagingProducts))
</div>*@




PenDesign.WebUI/Views/Project/List.cshtml
@using PenDesign.Common.HelperMethod
@model PenDesign.WebUI.Models.ProjectVM

@{
    ViewBag.Title = "Dự án";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

@section SEO{
    <meta name="keywords" content="@ViewBag.Keyword">
    <meta name="description" content="@ViewBag.Description">
    @Html.Raw(ViewBag.MetaData)
}

@section ScriptsHeader{

    <link href="~/Content/colorbox/colorbox.css" rel="stylesheet" />
    <script src="~/Content/colorbox/jquery.colorbox-min.js"></script>
}

<div class="content">
    <div class="container_12">
        <div class="breadcrumb">
            <a href="/" title="Trang chủ">Trang chủ</a> / Dự án
        </div>
        @*<div class="grid_12">
                <h2>Dự án</h2>
            </div>*@
        <div class="clear cl1"></div>
        <div class="serv">
            @if (Model.Project != null && Model.Project.Count() > 0)
            {
                var languageId = int.Parse(PenDesign.Common.Utils.Cookies.ReadCookie("PenDesign:Language", "129"));
                var i = 1;
                foreach (var item in Model.Project)
                {
                    <div class="grid_4">
                        @{
                            var projectNews = item.News.SingleOrDefault().NewsMappings.SingleOrDefault(nm => nm.LanguageId == languageId);
                            var title = projectNews.Title;
                            var intro = projectNews.Intro;

                            var detailUrl = "/du-an/" + XString.ToAscii(title) + "-" + item.Id;
                            var firstImage = item.ProjectImages.First();
                            if (item.ProjectImages.Where(pi => pi.Deleted == false).Count() > 0 && item.ProjectImages != null)
                            {
                                foreach (var image in item.ProjectImages)
                                {
                                    var imageName = image.ProjectImageMappings.Where(m => m.LanguageId == languageId && m.Status == true && m.Deleted == false).SingleOrDefault().Name;

                                    if (image.Equals(firstImage))
                                    {
                                        <a class="gal group-@i" href="@image.ResourceUrl" title="@imageName">
                                            <img src="@image.Thumbnail" class="img-responsive" alt="@imageName"/>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="group-@i hidden" href="@image.ResourceUrl" title="@imageName"></a>
                                    }
                                }
                            }

                        }
                        <div class="text1">
                            <a href="@detailUrl">@title</a>
                        </div>
                        @Html.Raw(intro)
                        <div class="alright">
                            <a href="@detailUrl" class="btn">Xem thêm</a>
                        </div>
                    </div>
                    if (i > 1 && i%3 == 0)
                    {
                        <div class="clear cl1"></div>
                    }
                    var content = "$('.group-" + i + "' ).colorbox({rel: 'group-" + i + "'});";
                    <script>
                        @Html.Raw(content)
                    </script>
                    i++;
                }
            }
            else
            {
                <p>Bài viết đang được cập nhật, vui lòng quay lại sau.</p>
            }

        </div>
        <div class="clear cl1"></div>
        @Html.Paging(new PagingOptions(Model.PagingItems.TotalPages))
    </div>
</div>








